#!/usr/bin/env bash
set -e
# Build and deploy for GitHub Pages (prebuilt files in repo root).
# Keeps index.html, 404.html, and assets/ in sync with the current build.
# Use index.source.html (entry: src/main.jsx) so Vite actually rebuilds from source;
# otherwise root index.html would point at an old bundle and the build would not recompile.

cp index.source.html index.html
npm run build

cp dist/index.html .
rm -rf assets
cp -r dist/assets .

# Sync 404.html to use the same hashed asset filenames as index.html
# (404.html is not generated by Vite; without this it would reference old bundles.)
JSFILE=$(grep -oE 'index-[a-zA-Z0-9_.-]+\.js' index.html | head -1)
CSSFILE=$(grep -oE 'index-[a-zA-Z0-9_.-]+\.css' index.html | head -1)
if [ -n "$JSFILE" ] && [ -f 404.html ]; then
  sed -i.bak "s|/assets/index-[^\"']*\.js|/assets/$JSFILE|" 404.html
  sed -i.bak "s|/assets/index-[^\"']*\.css|/assets/$CSSFILE|" 404.html
  rm -f 404.html.bak
fi

echo "Deploy done. Commit and push index.html, 404.html, and assets/ to publish."
